[package]
name = "openai-agents-rs"
version = "0.1.0"
edition = "2021"

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"

[[example]]
name = "tool_example"
path = "examples/tool_example.rs"

[[example]]
name = "calculator"
path = "examples/calculator.rs"

[[example]]
name = "multi_agent_research"
path = "examples/multi_agent_research.rs"

[[example]]
name = "session_with_guardrails"
path = "examples/session_with_guardrails.rs"

[[example]]
name = "persistent_session"
path = "examples/persistent_session.rs"

[[example]]
name = "parallel_tools"
path = "examples/parallel_tools.rs"

[dependencies]
async-openai = "0.29.0"
async-trait = "0.1"
tokio = { version = "1.41", features = ["full"] }
tokio-stream = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tracing = "0.1"
futures = "0.3"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.11", features = ["v4", "serde"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "sqlite",
    "chrono",
    "uuid",
] }

[dev-dependencies]
mockall = "0.13"
tokio-test = "0.4"
pretty_assertions = "1.4"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
