name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Cargo fetch
        run: cargo fetch

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Cargo check (all targets)
        run: cargo check --all --all-targets --all-features --locked

      - name: Run linter (clippy)
        run: cargo clippy --all --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all --all-features --locked

      - name: Doctests
        run: cargo test --doc --all --all-features --locked
