name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Restore sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Configure compiler cache
        run: |
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo "SCCACHE_CACHE_SIZE=1G" >> $GITHUB_ENV

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}-stable
          cache-on-failure: true

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run linter (clippy)
        run: cargo clippy --all --all-targets --all-features --locked -- -D warnings

      - name: Run tests
        run: cargo test --all-targets --all-features --doc --locked
